# Generated by Django 5.1 on 2024-08-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
