# Generated by Django 5.1 on 2024-09-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
